### PR TITLE
Bump deps and allow updating mongodb-odm

### PR DESCRIPTION
**Pull request by hairmare**
le_bump
> Yes sir! Major Bump, Sir! Attention!

### CODE REVIEW

**Comment by lapistano** [comment]
do we still use CentOS 6? If so there currently is only php 5.4 available via package manager. 
If there is a need for php >=5.5 we either need to compile it by oursleves.

**Comment by hairmare** [comment]
CentOS-7 is stable and it looks like it's safe to require it. Then again, where are you coming from? It's not like I depend on it here.

**Comment by lapistano** [comment]
I tried to composer install the branch in my VM, which is based on CentOS 6.x. This VM does not have PHP >= 5.5 in the standard repositories. 
So there is no 'easy' upgrade path in CentOS 6.x to use PHP in a newer version. 
The quintessence is more that I see a BC break, when merging this.

**Comment by hairmare** [comment]
The php-5.5 dep was introduced in 241027c9532e55a523964a6c9743ccc3de1a266f after I noticed that travis was breaking in it. This is where it first broke: https://travis-ci.org/libgraviton/GravitonRqlParserBundle/jobs/57790325. I'm not sure since when it wasn't working with 5.4 since we weren't on travis before then.

Anywhoo, since this has been changed there have been numerous PRs where this was not an issue. Why is it being raised now?

Personally I feel you should bump your dev machine. I currently don't see anywhere in our deploy pipeline where we can't have a current php as a dep. If we really need to re-add php-5.4 this PR is not the place for that, we should clarify our needs & open a proper story.

All this wants to do is use a sanely tagged version of ``doctrine/mongodb-odm``. It might well be we need to add some blockers on either ``symfony/translation`` or ``symfony/framework-bundle``.

**Comment by hairmare** [comment]
As discussed, I'll make this run under 5.4 again.

Please do note that this will only be worth something for a very short time. php-5.4 ist not being actively supported and will only get security-patches for the next 4 months. http://php.net/supported-versions.php

Come 14. Sept. we will have to drop 5.4 support completely anyhow.

**Comment by hairmare** [comment]
Ta

**Pull request merged**
